version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heroesdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3333:3306"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    environment:
      DB_VENDOR: mysql
      DB_ADDR: db
      DB_DATABASE: heroesdb
      DB_USER: user
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db
    command:
      - start-dev