client-id: my-client
resource-url: http://localhost:8080/realms/myrealm/protocol/openid-connect/token
grant-type: password

spring:
  datasource:
    url: jdbc:mysql://localhost:3333/heroesdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: my-client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/myrealm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8000


logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        boot: DEBUG
